export type {
  Game,
  GameMetadata,
  GameLifecycleState,
  GameCompletion,
  GameCompletionReason,
  GameResult,
  ScoreType,
  RankingPeriod,
} from "./types";
export { GAME_LIFECYCLE_STATES } from "./types";

export {
  isValidLifecycleTransition,
  assertValidLifecycleTransition,
  InvalidLifecycleTransitionError,
} from "./lifecycle";

export { GameSession, InvalidGameOperationError } from "./session";

export { validateGameResult, InvalidGameResultError } from "./result";

export {
  GameRegistry,
  validateGameMetadata,
  InvalidGameMetadataError,
  DuplicateGameError,
  GameNotFoundError,
} from "./registry";

export {
  MockGame,
  mockGameMetadata,
  type MockGameState,
  type MockGameInput,
  type MockGameResultMetadata,
} from "./games/mock-game";

export {
  ReactionTestGame,
  ReactionTestInputError,
  reactionTestMetadata,
  REACTION_TEST_MIN_DELAY_MS,
  REACTION_TEST_MAX_DELAY_MS,
  MathRandomDelaySource,
  REACTION_PHASES,
  type Clock,
  type RandomDelaySource,
  type ReactionPhase,
  type ReactionTestState,
  type ReactionTestInput,
  type ReactionTestResultMetadata,
} from "./games/reaction-test";

export {
  SwipeBrickBreakerGame,
  SwipeBrickBreakerInputError,
  swipeBrickBreakerMetadata,
  generateBricks,
  generateFormation,
  brickHpForLevel,
  newBrickCountForLevel,
  difficultyTierForLevel,
  DIFFICULTY_TIERS,
  type DifficultyTier,
  stepBalls,
  MathRandomSource,
  BOARD_COLS,
  BOARD_ROWS,
  BOARD_WIDTH,
  BOARD_HEIGHT,
  LAUNCH_MARGIN_ROWS,
  BRICK_TOP_MARGIN_ROWS,
  FORMATION_TOP_ROW,
  colToX,
  rowToY,
  BALL_RADIUS,
  BASE_BALL_SPEED,
  MAX_BALL_SPEED,
  MAX_NEW_BRICKS_PER_TURN,
  MAX_AIM_RADIANS,
  BALL_LAUNCH_STAGGER_MS,
  type RandomSource,
  type BrickHitEvent,
  type StepResult,
  type Brick,
  type Ball,
  type RedBonusBall,
  type SwipeBrickBreakerPhase,
  type SwipeBrickBreakerState,
  type SwipeBrickBreakerInput,
  type SwipeBrickBreakerResultMetadata,
} from "./games/swipe-brick-breaker";

export {
  MinesweeperGame,
  MinesweeperInputError,
  minesweeperMetadataFor,
  minesweeperEasyMetadata,
  minesweeperNormalMetadata,
  minesweeperHardMetadata,
  createEmptyBoard,
  neighborsOf,
  placeMines,
  revealCascade,
  safetyZoneOf,
  MINESWEEPER_DIFFICULTIES,
  MathRandomSource as MinesweeperMathRandomSource,
  type RandomSource as MinesweeperRandomSource,
  type MinesweeperDifficulty,
  type MinesweeperDifficultyConfig,
  type CellState as MinesweeperCellState,
  type Cell as MinesweeperCell,
  type MinesweeperPhase,
  type MinesweeperState,
  type MinesweeperInput,
  type MinesweeperResultMetadata,
} from "./games/minesweeper";

// Phase A only — see games/tetris/index.ts's own header comment. Not yet
// registered in gameRegistry.ts.
export {
  PIECE_TYPES,
  ROTATIONS,
  BOARD_WIDTH as TETRIS_BOARD_WIDTH,
  BOARD_HEIGHT as TETRIS_BOARD_HEIGHT,
  BUFFER_ROWS as TETRIS_BUFFER_ROWS,
  DEFAULT_GRAVITY_TABLE,
  DEFAULT_SCORING,
  DEFAULT_LINES_PER_LEVEL,
  DEFAULT_TETRIS_RULESET,
  SPAWN_X as TETRIS_SPAWN_X,
  SPAWN_Y as TETRIS_SPAWN_Y,
  spawnPiece,
  cellsForPiece,
  createEmptyBoard as createEmptyTetrisBoard,
  boardWidth as tetrisBoardWidth,
  boardHeight as tetrisBoardHeight,
  isInBounds as isTetrisCellInBounds,
  getCell as getTetrisCell,
  isCellEmpty as isTetrisCellEmpty,
  mergePieceIntoBoard,
  canPlace,
  getDropDistance,
  MathRandomSource as TetrisMathRandomSource,
  SevenBagGenerator,
  shuffledBag,
  PieceQueue,
  TetrisGame,
  tetrisMetadata,
  type RandomSource as TetrisRandomSource,
  type BagSource as TetrisBagSource,
  type PieceGenerator as TetrisPieceGenerator,
  type PieceType,
  type Rotation,
  type PieceCellOffset,
  type ActivePiece,
  type Cell as TetrisCell,
  type Board as TetrisBoard,
  type TetrisStatus,
  type TetrisState,
  type TetrisInput,
  type TetrisResultMetadata,
  type TetrisRuleset,
} from "./games/tetris";
